import React, { useCallback, useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { pushTasksApi } from '../../lib/pushTasksApi';
import { assignmentStatusLabel, canCompletePushTaskUi, canManagePushTaskUi, ownAssignment, taskProgress, taskStatusLabel } from '../../lib/pushTaskUi.mjs';
import PushTaskFormModal from './PushTaskFormModal';

const fmt = (value) => value ? new Intl.DateTimeFormat('de-DE',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)) : '—';
const badge = (level) => level===3?'bg-red-600 text-white':level===2?'bg-orange-500 text-white':level===1?'bg-amber-200 text-amber-950':'bg-black/5 text-black/60';
const eventLabel = (type) => ({created:'Erstellt',updated:'Bearbeitet',seen:'Gesehen',photo_uploaded:'Foto hochgeladen',submitted:'Zur Abnahme eingereicht',approved:'Bestätigt',rejected:'Abgelehnt',escalated:'Eskaliert',deescalated:'Deeskaliert',cancelled:'Abgebrochen'}[type]||type);

export default function PushTaskCenter({ user, compact=false }) {
  const [tasks,setTasks]=useState([]),[users,setUsers]=useState([]),[notifications,setNotifications]=useState([]);
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[tab,setTab]=useState('mine');
  const [selected,setSelected]=useState(null),[formOpen,setFormOpen]=useState(false),[editTask,setEditTask]=useState(null);
  const [comment,setComment]=useState(''),[photo,setPhoto]=useState(null),[deesc,setDeesc]=useState({reason:'',until:'',level:0});

  const load=useCallback(async()=>{try{const [taskData,userData,noteData]=await Promise.all([pushTasksApi.list(),pushTasksApi.users(),pushTasksApi.notifications()]);setTasks(taskData.tasks||[]);setUsers(userData.users||[]);setNotifications(noteData.notifications||[]);setSelected((current)=>current?(taskData.tasks||[]).find((item)=>item.id===current.id)||null:null);}catch(error){toast.error(error.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer);},[load]);

  const visible=useMemo(()=>tasks.filter((task)=>{
    const own=ownAssignment(task,user.id);
    if(tab==='mine')return own&&task.status==='active';
    if(tab==='created')return Number(task.created_by_user_id)===Number(user.id);
    if(tab==='approvals')return Number(task.created_by_user_id)===Number(user.id)&&(task.assignments||[]).some((item)=>item.status==='submitted');
    return true;
  }),[tasks,tab,user.id]);
  const unread=notifications.filter((item)=>!item.read_at).length;

  const saveTask=async(payload)=>{setSaving(true);try{const editing=Boolean(editTask);await(editing?pushTasksApi.update(editTask.id,payload):pushTasksApi.create(payload));if(!editing)setTab('created');toast.success(editing?'Task aktualisiert.':'Task erstellt und unter „Von mir erstellt“ geöffnet.');setFormOpen(false);setEditTask(null);await load();}catch(error){toast.error(error.message);}finally{setSaving(false);}};
  const run=async(action,success)=>{setSaving(true);try{await action();toast.success(success);await load();}catch(error){toast.error(error.message);}finally{setSaving(false);}};
  const submitOwn=async(task)=>{const own=ownAssignment(task,user.id);await run(async()=>{if(photo)await pushTasksApi.uploadPhoto(task.id,own.id,photo);await pushTasksApi.submit(task.id,comment);setPhoto(null);setComment('');},'Erledigung zur Abnahme eingereicht.');};
  const deescalate=async(task)=>{if(!deesc.reason||!deesc.until)return toast.error('Grund und Wiedervorlage fehlen.');await run(()=>pushTasksApi.deescalate(task.id,{reason:deesc.reason,snoozed_until:new Date(deesc.until).toISOString(),level:Number(deesc.level)}),'Task deeskaliert.');setDeesc({reason:'',until:'',level:0});};

  return <section className={`${compact?'':'min-h-screen bg-[#3A3838] p-3 sm:p-8'} text-black`}>
    <div className="mx-auto max-w-7xl overflow-hidden rounded-2xl bg-white/95 shadow-2xl backdrop-blur">
      <header className="flex flex-col gap-3 bg-[#800000] p-4 text-white sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-white/65">Pilot · Admin & Supervisor</div><h2 className="text-2xl font-black sm:text-3xl">Pushtasks</h2><p className="text-sm text-white/75">Verbindlich, nachvollziehbar und mit Einzelabnahme.</p></div><button onClick={()=>{setEditTask(null);setFormOpen(true);}} className="min-h-11 rounded-xl bg-white px-5 font-bold text-[#800000]">Neue Task</button></header>
      <nav className="flex gap-2 overflow-x-auto border-b p-3 text-sm font-bold">{[['mine','Meine offenen'],['created','Von mir erstellt'],['approvals','Abnahmen'],['all','Alle']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-lg px-3 py-2 ${tab===id?'bg-[#800000] text-white':'bg-black/5'}`}>{label}{id==='approvals'&&tasks.filter((t)=>Number(t.created_by_user_id)===Number(user.id)&&(t.assignments||[]).some((a)=>a.status==='submitted')).length>0?' ●':''}</button>)}<button onClick={()=>setTab('notifications')} className={`ml-auto whitespace-nowrap rounded-lg px-3 py-2 ${tab==='notifications'?'bg-[#800000] text-white':'bg-black/5'}`}>Hinweise {unread?`(${unread})`:''}</button></nav>
      <div className="max-h-[58vh] overflow-auto p-3 sm:p-5">
        {loading?<div className="p-8 text-center text-black/50">Pushtasks werden geladen…</div>:tab==='notifications'?<div className="grid gap-2">{notifications.length?notifications.map((note)=><button key={note.id} onClick={()=>run(()=>pushTasksApi.markRead(note.id),'Hinweis gelesen.')} className={`rounded-xl border p-4 text-left ${note.read_at?'opacity-55':'border-[#800000]/40 bg-red-50'}`}><div className="font-bold">{note.title}</div><div className="text-sm">{note.body}</div><div className="mt-1 text-xs text-black/50">{fmt(note.created_at)}</div></button>):<Empty text="Keine Hinweise." />}</div>
        :visible.length?<div className="grid gap-3 lg:grid-cols-2">{visible.map((task)=>{const progress=taskProgress(task),own=ownAssignment(task,user.id),mayManage=canManagePushTaskUi(task,user)&&task.status==='active',mayComplete=canCompletePushTaskUi(task,user),maxLevel=Math.max(0,...(task.assignments||[]).map((a)=>Number(a.escalation_level||0))),open=()=>{setSelected(task);if(own&&own.status==='open')run(()=>pushTasksApi.seen(task.id),'Task als gesehen markiert.');};return <article key={task.id} className="rounded-xl border p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><button type="button" onClick={open} className="block w-full text-left"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-wide text-[#800000]">{task.priority==='critical'?'Kritisch':task.priority==='high'?'Hohe Priorität':'Pushtask'}</div><h3 className="text-lg font-black">{task.title}</h3></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${badge(maxLevel)}`}>Stufe {maxLevel}</span></div><p className="mt-2 line-clamp-2 text-sm text-black/65">{task.description}</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded bg-black/5 px-2 py-1">Fällig {fmt(task.due_at)}</span><span className="rounded bg-black/5 px-2 py-1">{progress.approved}/{progress.total} bestätigt</span>{own&&<span className="rounded bg-black/5 px-2 py-1">Ich: {assignmentStatusLabel(own.status)}</span>}<span className="rounded bg-black/5 px-2 py-1">{taskStatusLabel(task.status)}</span></div></button><div className="mt-4 flex flex-col gap-2 border-t pt-3 sm:flex-row">{mayManage&&<button type="button" onClick={()=>{setEditTask(task);setFormOpen(true);}} className="min-h-11 flex-1 rounded-lg border border-[#800000] px-4 py-2 font-bold text-[#800000]">Bearbeiten</button>}<button type="button" onClick={open} className="min-h-11 flex-1 rounded-lg bg-[#800000] px-4 py-2 font-bold text-white">{mayComplete?'Öffnen und erledigen':'Öffnen'}</button></div></article>})}</div>:<Empty text="In diesem Bereich gibt es aktuell keine Tasks." />}
      </div>
    </div>
    <PushTaskFormModal open={formOpen} users={users} task={editTask} saving={saving} onClose={()=>{setFormOpen(false);setEditTask(null);}} onSave={saveTask}/>
    {selected&&<TaskDetail task={selected} user={user} saving={saving} comment={comment} setComment={setComment} photo={photo} setPhoto={setPhoto} deesc={deesc} setDeesc={setDeesc} onClose={()=>setSelected(null)} onSubmit={()=>submitOwn(selected)} onReview={(assignment,action)=>{const reason=action==='reject'?window.prompt('Begründung der Ablehnung:')||'':'';if(action==='reject'&&!reason)return;run(()=>pushTasksApi.review(selected.id,assignment.id,action,reason),action==='approve'?'Erledigung bestätigt.':'Erledigung abgelehnt.');}} onEdit={()=>{setEditTask(selected);setFormOpen(true);setSelected(null);}} onDeescalate={()=>deescalate(selected)} onCancel={()=>{const reason=window.prompt('Begründung für den Abbruch:');if(reason)run(()=>pushTasksApi.cancel(selected.id,reason),'Task abgebrochen.');}}/>}
  </section>;
}

function Empty({text}){return <div className="rounded-xl border border-dashed p-10 text-center text-black/45">{text}</div>}

function TaskDetail({task,user,saving,comment,setComment,photo,setPhoto,deesc,setDeesc,onClose,onSubmit,onReview,onEdit,onDeescalate,onCancel}){
  const own=ownAssignment(task,user.id),isCreator=Number(task.created_by_user_id)===Number(user.id),canManage=canManagePushTaskUi(task,user);
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/75 p-2 sm:p-6" role="dialog" aria-modal="true"><div className="max-h-[96vh] w-full max-w-5xl overflow-auto rounded-2xl bg-white p-4 sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.18em] text-[#800000]">{taskStatusLabel(task.status)} · Fällig {fmt(task.due_at)}</div><h2 className="text-2xl font-black sm:text-3xl">{task.title}</h2><div className="text-sm text-black/50">Erstellt von {task.creator_name}</div></div><button onClick={onClose} className="rounded-lg px-3 py-2 hover:bg-black/5">Schließen</button></div><p className="mt-4 whitespace-pre-wrap rounded-xl bg-black/5 p-4">{task.description}</p>
    <div className="mt-5 grid gap-3">{(task.assignments||[]).map((a)=><div key={a.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="font-bold">{a.assignee_name} <span className="font-normal text-black/45">({a.assignee_role})</span></div><div className="flex gap-2"><span className={`rounded-full px-2 py-1 text-xs font-bold ${badge(a.escalation_level)}`}>Stufe {a.escalation_level}</span><span className="rounded-full bg-black/5 px-2 py-1 text-xs font-bold">{assignmentStatusLabel(a.status)}</span></div></div>{a.submission_comment&&<div className="mt-2 text-sm">Kommentar: {a.submission_comment}</div>}{a.review_comment&&<div className="mt-2 text-sm text-[#800000]">Prüfung: {a.review_comment}</div>}{(a.evidence||[]).map((e)=><button key={e.id} onClick={()=>pushTasksApi.openEvidence(task.id,e.id).catch((x)=>toast.error(x.message))} className="mt-2 mr-2 rounded-lg bg-black/5 px-3 py-2 text-sm font-bold">📷 {e.file_name}</button>)}{isCreator&&a.status==='submitted'&&<div className="mt-3 flex gap-2"><button disabled={saving} onClick={()=>onReview(a,'approve')} className="rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white">Bestätigen</button><button disabled={saving} onClick={()=>onReview(a,'reject')} className="rounded-lg bg-red-600 px-4 py-2 font-bold text-white">Ablehnen</button></div>}</div>)}</div>
    {own&&task.status==='active'&&!['submitted','approved'].includes(own.status)&&<div className="mt-5 rounded-xl border-2 border-[#800000]/20 p-4"><h3 className="font-black">Meine Erledigung einreichen</h3>{task.proof_mode!=='confirm'&&<label className="mt-3 block text-sm">Fotonachweis (JPG, PNG oder WebP, maximal 5 MB)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>setPhoto(e.target.files?.[0]||null)} className="mt-1 block w-full"/></label>}<textarea value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="Kommentar zur Erledigung (optional)" className="mt-3 w-full rounded-lg border p-3"/><button disabled={saving||(task.proof_mode!=='confirm'&&!photo)} onClick={onSubmit} className="mt-3 rounded-lg bg-[#800000] px-5 py-3 font-bold text-white disabled:opacity-50">Zur Abnahme einreichen</button></div>}
    {(task.events||[]).length>0&&<div className="mt-5 rounded-xl bg-black/[.035] p-4"><h3 className="font-black">Verlauf</h3><ol className="mt-3 grid gap-2">{task.events.map((event)=><li key={event.id} className="flex flex-col rounded-lg bg-white p-3 text-sm sm:flex-row sm:items-center sm:justify-between"><span><strong>{eventLabel(event.event_type)}</strong>{event.actor_name?` · ${event.actor_name}`:''}</span><time className="text-xs text-black/45">{fmt(event.created_at)}</time></li>)}</ol></div>}
    {canManage&&task.status==='active'&&<div className="mt-5 rounded-xl bg-amber-50 p-4"><h3 className="font-black">Verwaltung</h3><div className="mt-3 flex flex-wrap gap-2"><button onClick={onEdit} className="rounded-lg bg-white px-4 py-2 font-bold shadow">Bearbeiten</button><button onClick={onCancel} className="rounded-lg bg-white px-4 py-2 font-bold text-red-700 shadow">Abbrechen</button></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><input value={deesc.reason} onChange={(e)=>setDeesc({...deesc,reason:e.target.value})} placeholder="Grund der Deeskalation" className="rounded-lg border p-2"/><input type="datetime-local" value={deesc.until} onChange={(e)=>setDeesc({...deesc,until:e.target.value})} className="rounded-lg border p-2"/><select value={deesc.level} onChange={(e)=>setDeesc({...deesc,level:e.target.value})} className="rounded-lg border p-2"><option value="0">Zurück auf Stufe 0</option><option value="1">Zurück auf Stufe 1</option><option value="2">Zurück auf Stufe 2</option></select></div><button onClick={onDeescalate} className="mt-2 rounded-lg bg-amber-600 px-4 py-2 font-bold text-white">Deeskalieren</button></div>}
  </div></div>;
}
